[package]
name = "bluesnow"
version = "0.1.0"
authors = ["Jack Halford <jack@crans.org>", "William Escande <wescande@student.42.fr>"]

[lib]
crate-type = ["staticlib"]

[profile.release]
panic = "abort"

[dependencies]
